version: '3.8'

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://db:27017/mydatabase
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mongo:7
    restart: always
    volumes:
      - db-data:/data/db

volumes:
  db-data:
