version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    image: syafiqahlukman/test:latest
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://db:27017/mydatabase

volumes:
  mongo-data: