version: '3.8'

services:
  app:
    environment:
      MONGO_URI: mongodb://db:27017/mydatabase
    image: syafiqahlukman/test:latest
    ports:
      - published: 8080
        target: 8080

  mongo:
    image: mongo:latest
    ports:
      - published: 27017
        target: 27017
    volumes:
      - mongo-data:/data/db

  nginx:
    depends_on:
      - app
    image: nginx:latest
    ports:
      - published: 80
        target: 80

volumes:
  mongo-data:
